### ISSUE TITLE
[question] Is it possible to disable? Using ng-disabled for example.

### ISSUE THREAD

**Issue by paulocheque** [xpepermint/angular-ui-switch#15]
Is it possible to disable? Using ng-disabled for example.

    <switch id="enabled" name="enabled" ng-model="mymodel" ng-disabled="true"></switch>

**Comment by JobaDiniz** [comment]
Related: https://github.com/xpepermint/angular-ui-switch/issues/9

**Comment by xpepermint** [comment]
https://github.com/xpepermint/angular-ui-switch/pull/23
