### ISSUE TITLE
Improve Accessibility

### ISSUE THREAD

**Issue by kentcdodds** [xpepermint/angular-ui-switch#20]
By putting `display: none` on the input element, screen readers can't access it. See what [this post](http://codersblock.com/blog/checkbox-trickery-with-css) does to accomplish the same thing in an accessible way:

> ``` css
> input {
>     position: absolute;
>     left: -9999px;
> }
> ```
> 
> Why not display: none? Because that would cause it to be ignored by screen readers and keyboard tabbing. This method keeps <input> in the flow, but hides it offscreen.

**Comment by xpepermint** [comment]
Hey @kentcdodds. I work on other projects thus I can not devote enough time to this one. Would you be interested in `collaborator` role?

**Comment by kentcdodds** [comment]
I no longer need this either actually. Thanks anyway! I'll leave it open so someone can see this is needed in the future and perhaps implement it themselves.
