### ISSUE TITLE
How do i disable or make this control readonly

### ISSUE THREAD

**Issue by rakeshch** [xpepermint/angular-ui-switch#22]
Hi,

I like the control. It's simple to use. But only problem is I am not able to set ng-disabled/ readonly property on this control?

Thanks,
Rakesh

**Comment by rakeshch** [comment]
never mind. i just saw a reference in the earlier question.

Thanks,
Rakesh

**Comment by rakeshch** [comment]
referring to question #9

**Comment by gajanak** [comment]
I needed to use one-way binding. its a very small change:
It's some kind of read-only ;)

replace
html +=   ' ng-class="{ checked:' + attrs.ngModel  + ' }"';
by
html +=   ' ng-class="{ checked:' + (attrs.ngModel || attrs.state ) + ' }"';

now you can remove ng-model  and set <switch state="ctrl.state" ng-click="ctrl.enable()" >

Perhaps this helps someone else too.

**Comment by scamjayi** [comment]
I have the same problem. It would be great if you could fix it.

**Comment by xpepermint** [comment]
https://github.com/xpepermint/angular-ui-switch/pull/23

**Comment by rakeshch** [comment]
Awesome, thanks so much.
