### ISSUE TITLE
change the switch from a controller after function is done

### ISSUE THREAD

**Issue by artdias90** [xpepermint/angular-ui-switch#30]
I have the switch as a component in my controller, and I would like to change its status inside this controller, after cheking a htp request. How can this be done? I try to change the model of the switch but nothing happens.

**Comment by EskoCruz** [comment]
You should be able to take the model name into the controller and since its a boolean, change it true or false. Switch out whats in the curly braces with your component names.

```
.controller('{ControllerName}', function($scope) {
    $scope.{ngModelSwitchName} = true;
}
```

**Comment by artdias90** [comment]
Problem is the following,

``` javascript
$scope.switchMode = function(offline) {
            // try a HTTP connection
            authService.request().then(function(response) {
                if(response.status == 0) {
                    $scope.{ngModelSwitchName}=!$scope.{ngModelSwitchName};
                } else {
                    // tell rootScope we are switched
                    $rootScope.$broadcast('changedMode');
                }
            });
        };
```

Basically if i turn the switch, but my http request failed, I want to turn the switch back.

Ideally, I would like to not change the switch model at all, until this request is done

**Comment by artdias90** [comment]
UPDATE: to fix that I removed the checkbox from the diective. I will close this
